name: Deploy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish-firefox:
    name: Publish Firefox extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set version
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${GITHUB_REF#refs/*/}\"/g" manifest.json
      
      - name: Build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .
          filename: no-medium-login.zip
      
      - name: Publish
        uses: yayuyokitano/firefox-addon@v0.0.6-alpha
        with:
          api_key: ${{ secrets.JWT_ISSUER }}
          api_secret: ${{ secrets.JWT_SECRET }}
          guid: '{9338c206-3387-482b-bf92-5e2a157fd5be}'
          xpi_path: web-ext-artifacts/no-medium-login.zip
